# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "cbor",
    srcs = [
        "src/lib.rs",
        "src/macros.rs",
        "src/reader.rs",
        "src/values.rs",
        "src/writer.rs",
    ],
)

