[workspace]
members = [
    "cryptotest",
    "opentitanlib",
    "opentitanlib/bindgen",
    "opentitanlib/opentitantool_derive",
    "opentitantool",
    "opentitansession",
    "tpm2_test_server"
]
