package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logo_ibex",
    hdrs = [
        "ibex_logo.h",
    ],
)

cc_library(
    name = "logo_opentitan_160_39px",
    hdrs = [
        "logo_opentitan_160_39.h",
    ],
)

cc_library(
    name = "logo_lowrisc_05_80px",
    hdrs = [
        "lowrisc_logo_105_80.h",
    ],
)

cc_library(
    name = "shape_opentitan_80_80px",
    hdrs = [
        "ot_shape_80x80.h",
    ],
)

cc_library(
    name = "logo_tux_80_95px",
    hdrs = [
        "logo_tux_80_95.h",
    ],
)

cc_library(
    name = "stronks_160_107px",
    hdrs = [
        "stronks_160_107.h",
    ],
)

cc_library(
    name = "ot_stronks_160_100px",
    hdrs = [
        "ot_stronks_160_100.h",
    ],
)